---
# Node Exporter Installation Role for Prometheus Monitoring

- name: Create node_exporter user
  ansible.builtin.user:
    name: node_exporter
    system: yes
    shell: /sbin/nologin
    create_home: no
  tags:
    - node_exporter

- name: Download node_exporter
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: /tmp/node_exporter-{{ node_exporter_version }}.tar.gz
    mode: "0644"
  tags:
    - node_exporter

- name: Extract node_exporter
  ansible.builtin.unarchive:
    src: /tmp/node_exporter-{{ node_exporter_version }}.tar.gz
    dest: /tmp
    remote_src: yes
  tags:
    - node_exporter

- name: Install node_exporter binary
  ansible.builtin.copy:
    src: /tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter
    dest: /usr/local/bin/node_exporter
    owner: root
    group: root
    mode: "0755"
    remote_src: yes
  notify: Restart node_exporter
  tags:
    - node_exporter

- name: Create node_exporter systemd service
  ansible.builtin.template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload systemd
    - Restart node_exporter
  tags:
    - node_exporter

- name: Enable and start node_exporter
  ansible.builtin.systemd:
    name: node_exporter
    state: started
    enabled: yes
    daemon_reload: yes
  when: node_exporter_enabled | default(true)
  tags:
    - node_exporter

- name: Clean up temporary files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /tmp/node_exporter-{{ node_exporter_version }}.tar.gz
    - /tmp/node_exporter-{{ node_exporter_version }}.linux-amd64
  tags:
    - node_exporter

- name: Verify node_exporter is running
  ansible.builtin.uri:
    url: "http://localhost:{{ node_exporter_port }}/metrics"
    status_code: 200
  register: node_exporter_check
  ignore_errors: yes
  tags:
    - node_exporter
    - verify
