---
# Node Exporter handlers

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart node_exporter
  ansible.builtin.systemd:
    name: node_exporter
    state: restarted
